services:
  db:
    image: postgres:17.6-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: montre
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: main
    ports:
      - 54332:5432
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
