ktor:
    application:
        modules:
            - com.example.DataSourceKt.module
    deployment:
        port: 8080
db:
    url: "jdbc:postgresql://localhost:54332/main"
    user: "montre"
    password: "P@ssw0rd"
    driver: "org.postgresql.Driver"
    pool:
        maxSize: 10
