[versions]
kotlin = "2.2.20"
groovy = "3.0.25"
ktor = "3.3.2"
koin-bom = "4.1.1"
koin-annotations = "2.3.1"
logback = "1.5.21"
kotlinx-serialization-json = "1.9.0"
postgresql = "42.7.8"
hikari = "7.0.2"
flyway = "11.18.0"
jooq = "3.20.9"
database-rider = "1.44.0"
snakeyaml = "2.5"
jackson = "2.20.1"
junit-jupiter-api = "6.0.1"
mokk = "1.14.7"
ksp = "2.3.3"
dagger-compiler = "2.51.1"

[libraries]
# main
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-ktor = { module = "io.insert-koin:koin-ktor" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations" }
koin-ksp-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotations" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
jooq = { module = "org.jooq:jooq", version.ref = "jooq" }
jooq-meta = { module = "org.jooq:jooq-meta", version.ref = "jooq" }
mokk = { module = "io.mockk:mockk", version.ref = "mokk" }

# test
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter-api"}
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
rider-core = { module = "com.github.database-rider:rider-core", version.ref = "database-rider" }
rider-junit5 = { module = "com.github.database-rider:rider-junit5", version.ref = "database-rider" }
groovy = { module = "org.codehaus.groovy:groovy-all", version.ref = "groovy" }
# caused by a vulnerable transitive library from rider-core
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
# caused by a vulnerable transitive library from rider-core
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway" }
jooq-codegen = { id = "org.jooq.jooq-codegen-gradle", version.ref = "jooq" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
